/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { KOLSkill } from "./types";

export const SKILL_POOL: KOLSkill[] = [
  // --- NGHỆ THUẬT & TRUYỀN THÔNG (ART & MEDIA) ---
  { name: "Thần Thái Thiên Tiên", description: "Tỏa ra hào quang khiến người xem không thể rời mắt.", effect: "+30% Engagement", cooldown: "Passive", level: 1 },
  { name: "Vũ Điệu Nghê Thường", description: "Điệu nhảy làm say đắm lòng người, tăng mạnh tương tác.", effect: "+50% Viral Chance", cooldown: "120s", level: 1 },
  { name: "Họa Hồn Bút", description: "Vẽ ra những hình ảnh sống động như thật.", effect: "+40% Content Quality", cooldown: "180s", level: 1 },
  { name: "Tiếng Đàn Phục Hy", description: "Âm nhạc chữa lành tâm hồn người nghe.", effect: "+20% Loyalty", cooldown: "300s", level: 1 },
  { name: "Ảo Ảnh Chi Thuật", description: "Tạo ra các hiệu ứng hình ảnh kỳ ảo.", effect: "+25% Visual Appeal", cooldown: "60s", level: 1 },
  { name: "Cầm Kỳ Thi Họa", description: "Tinh thông tứ nghệ, nâng tầm đẳng cấp nội dung.", effect: "+35% Prestige", cooldown: "Passive", level: 1 },
  { name: "Sắc Diện Vạn Biến", description: "Thay đổi phong cách trang điểm trong chớp mắt.", effect: "+20% Versatility", cooldown: "30s", level: 1 },
  { name: "Thanh Âm Diệu Gợi", description: "Giọng nói truyền cảm hứng, giữ chân người xem lâu hơn.", effect: "+45% Retention", cooldown: "Passive", level: 1 },
  { name: "Vũ Điệu Ánh Sáng", description: "Điều khiển ánh sáng studio bằng ý nghĩ.", effect: "+30% Aesthetic", cooldown: "60s", level: 1 },
  { name: "Kịch Bản Thiên Định", description: "Tạo ra những cốt truyện video không thể cưỡng lại.", effect: "+55% Completion Rate", cooldown: "600s", level: 1 },
  { name: "Góc Quay Thần Thánh", description: "Luôn tìm thấy góc mặt đẹp nhất trong mọi hoàn cảnh.", effect: "+20% Beauty Score", cooldown: "Passive", level: 1 },
  { name: "Biên Tập Siêu Tốc", description: "Hoàn thành video triệu view chỉ trong vài phút.", effect: "+40% Productivity", cooldown: "300s", level: 1 },
  { name: "Màu Sắc Ma Thuật", description: "Phối màu video gây nghiện cho thị giác.", effect: "+30% Eye-Catching", cooldown: "Passive", level: 1 },
  { name: "Diễn Xuất Xuất Thần", description: "Nhập vai hoàn hảo vào bất kỳ concept nào.", effect: "+40% Authenticity", cooldown: "120s", level: 1 },
  { name: "Âm Nhạc Gây Nghiện", description: "Chọn nhạc nền khiến người xem phải nghe đi nghe lại.", effect: "+50% Replay Value", cooldown: "Passive", level: 1 },
  { name: "Thiết Kế Vị Lai", description: "Tạo ra các bộ trang phục mang phong cách Cyber-Xianxia.", effect: "+35% Uniqueness", cooldown: "600s", level: 1 },
  { name: "Nghệ Thuật Sắp Đặt", description: "Biến mọi không gian thành studio chuyên nghiệp.", effect: "+25% Professionalism", cooldown: "Passive", level: 1 },
  { name: "Luồng Sáng Neon", description: "Tạo hiệu ứng ánh sáng neon bao quanh cơ thể.", effect: "+40% Cyber Vibe", cooldown: "45s", level: 1 },
  { name: "Vũ Điệu Hologram", description: "Khiêu vũ cùng các bản sao kỹ thuật số.", effect: "+60% Wow Factor", cooldown: "180s", level: 1 },
  { name: "Truyền Thuyết Đô Thị", description: "Kể chuyện ma mị, thu hút lượng lớn người xem tò mò.", effect: "+45% Curiosity", cooldown: "300s", level: 1 },

  // --- CÔNG NGHỆ & KỸ THUẬT SỐ (TECH & CYBER) ---
  { name: "Giao Diện Thần Kinh", description: "Kết nối trực tiếp với tâm trí người xem.", effect: "+60% Conversion", cooldown: "360s", level: 1 },
  { name: "Hack Luồng Dữ Liệu", description: "Chiếm lĩnh các vị trí hot trên bảng tin.", effect: "Trend Hijack", cooldown: "600s", level: 1 },
  { name: "Phân Tích Đa Chiều", description: "Dự đoán chính xác xu hướng tương lai.", effect: "Trend Prediction", cooldown: "Passive", level: 1 },
  { name: "Lá Chắn Tường Lửa", description: "Bảo vệ danh tiếng khỏi các scandal.", effect: "Anti-Scandal", cooldown: "Passive", level: 1 },
  { name: "Siêu Máy Tính Sinh Học", description: "Xử lý hàng triệu yêu cầu cùng lúc.", effect: "Multi-Stream", cooldown: "Passive", level: 1 },
  { name: "Thuật Toán Tối Ưu", description: "Luôn xuất hiện đầu tiên trên trang tìm kiếm.", effect: "SEO Mastery", cooldown: "Passive", level: 1 },
  { name: "Mạng Lưới Bot Fan", description: "Triệu hồi hàng ngàn bot để tăng tương tác ảo.", effect: "+100% Vanity Stats", cooldown: "1200s", level: 1 },
  { name: "Dịch Thuật Tức Thời", description: "Nói chuyện với fan toàn cầu bằng mọi ngôn ngữ.", effect: "Global Reach", cooldown: "Passive", level: 1 },
  { name: "Thực Tế Tăng Cường", description: "Mang sản phẩm đến tận tay người xem qua AR.", effect: "+50% Experience", cooldown: "300s", level: 1 },
  { name: "Mã Hóa Cảm Xúc", description: "Gửi tín hiệu cảm xúc trực tiếp qua màn hình.", effect: "+40% Emotional Impact", cooldown: "180s", level: 1 },
  { name: "Linh Hồn Kỹ Thuật Số", description: "Tồn tại vĩnh viễn trên mạng internet.", effect: "Immortality", cooldown: "Passive", level: 1 },
  { name: "Tường Lửa Danh Tính", description: "Ẩn danh hoàn toàn khi cần thiết.", effect: "Anonymity", cooldown: "600s", level: 1 },
  { name: "Đám Mây Tri Thức", description: "Truy cập mọi thông tin trên thế giới trong 1 giây.", effect: "Omniscience", cooldown: "Passive", level: 1 },
  { name: "Cổng Không Gian Data", description: "Di chuyển dữ liệu siêu tốc, không bao giờ lag.", effect: "Zero Latency", cooldown: "Passive", level: 1 },
  { name: "Bóng Ma Kỹ Thuật Số", description: "Xóa sạch mọi dấu vết tiêu cực trên mạng.", effect: "Digital Cleanse", cooldown: "3600s", level: 1 },
  { name: "Trí Tuệ Nhân Tạo Đồng Hành", description: "Có một AI trợ lý thông minh hỗ trợ 24/7.", effect: "+30% Efficiency", cooldown: "Passive", level: 1 },
  { name: "Mạng Lưới 6G Tâm Linh", description: "Kết nối sóng não với tốc độ ánh sáng.", effect: "+50% Connection", cooldown: "Passive", level: 1 },
  { name: "Virus Viral", description: "Phát tán nội dung như một loại virus không thể ngăn chặn.", effect: "Exponential Growth", cooldown: "2400s", level: 1 },
  { name: "Lá Chắn Chống Deepfake", description: "Bảo vệ hình ảnh cá nhân khỏi bị giả mạo.", effect: "Authenticity Guard", cooldown: "Passive", level: 1 },
  { name: "Năng Lượng Pin Vĩnh Cửu", description: "Livestream liên tục 100 giờ không cần nghỉ.", effect: "Infinite Stamina", cooldown: "Passive", level: 1 },

  // --- KINH DOANH & THƯƠNG HIỆU (BUSINESS & EMPIRE) ---
  { name: "Miệng Lưỡi Vàng", description: "Thuyết phục bất kỳ ai mua hàng.", effect: "+100% Sales", cooldown: "300s", level: 1 },
  { name: "Mạng Lưới Vạn Vật", description: "Kết nối với hàng ngàn nhãn hàng.", effect: "+40% Sponsorship", cooldown: "Passive", level: 1 },
  { name: "Thao Túng Thị Trường", description: "Điều khiển giá cả theo ý muốn.", effect: "Price Control", cooldown: "1200s", level: 1 },
  { name: "Đế Chế Truyền Thông", description: "Tự tạo ra các xu hướng mới.", effect: "Trend Creation", cooldown: "2400s", level: 1 },
  { name: "Tầm Nhìn Tỷ Phú", description: "Nhìn thấy cơ hội ở khắp mọi nơi.", effect: "+50% Profit", cooldown: "Passive", level: 1 },
  { name: "Hợp Đồng Kim Cương", description: "Luôn nhận được những deal quảng cáo giá trị nhất.", effect: "+60% Income", cooldown: "Passive", level: 1 },
  { name: "Thương Hiệu Cá Nhân", description: "Tên tuổi trở thành bảo chứng cho chất lượng.", effect: "+40% Trust", cooldown: "Passive", level: 1 },
  { name: "Độc Quyền Phân Phối", description: "Chỉ bạn mới có quyền bán những siêu phẩm.", effect: "Monopoly", cooldown: "Passive", level: 1 },
  { name: "Chiến Lược Đại Dương Xanh", description: "Tìm ra thị trường ngách không có đối thủ.", effect: "No Competition", cooldown: "Passive", level: 1 },
  { name: "Quản Trị Rủi Ro", description: "Biến khủng hoảng thành cơ hội làm giàu.", effect: "Crisis Profit", cooldown: "1800s", level: 1 },
  { name: "Mạng Lưới Quan Hệ", description: "Quen biết tất cả các ông trùm công nghệ.", effect: "+30% Influence", cooldown: "Passive", level: 1 },
  { name: "Đầu Tư Thiên Tài", description: "Tiền tự đẻ ra tiền khi bạn đang ngủ.", effect: "Passive Income", cooldown: "Passive", level: 1 },
  { name: "Đấu Giá Thần Tốc", description: "Luôn giành được những món hàng hời nhất.", effect: "Auction Win", cooldown: "600s", level: 1 },
  { name: "Tâm Lý Khách Hàng", description: "Biết chính xác khách hàng muốn tiêu tiền vào đâu.", effect: "+45% Conversion", cooldown: "Passive", level: 1 },
  { name: "Bí Mật Kinh Doanh", description: "Sở hữu những công thức độc quyền không ai có.", effect: "Unique Selling Point", cooldown: "Passive", level: 1 },
  { name: "Thuyết Phục Nhà Đầu Tư", description: "Gọi vốn thành công chỉ sau 1 phút trình bày.", effect: "Easy Funding", cooldown: "3600s", level: 1 },
  { name: "Tối Ưu Hóa Chi Phí", description: "Vận hành đế chế với chi phí thấp nhất.", effect: "+20% Margin", cooldown: "Passive", level: 1 },
  { name: "Mở Rộng Quy Mô", description: "Nhân bản mô hình kinh doanh ra toàn cầu.", effect: "Global Expansion", cooldown: "Passive", level: 1 },
  { name: "Lòng Trung Thành Khách Hàng", description: "Khách hàng sẽ không bao giờ rời bỏ bạn.", effect: "+80% Retention", cooldown: "Passive", level: 1 },
  { name: "Biểu Tượng Văn Hóa", description: "Trở thành gương mặt đại diện cho cả một thế hệ.", effect: "Cultural Icon", cooldown: "Passive", level: 1 },

  // --- TÂM LINH & CẢM XÚC (SPIRITUAL & MYSTIC) ---
  { name: "Tiên Tri Thuật", description: "Biết trước những gì người xem muốn.", effect: "Mind Reading", cooldown: "Passive", level: 1 },
  { name: "Tẩy Não Chi Thuật", description: "Khiến người xem tin tưởng tuyệt đối.", effect: "Absolute Trust", cooldown: "600s", level: 1 },
  { name: "Luân Hồi Chuyển Thế", description: "Có khả năng tái sinh danh tiếng sau thất bại.", effect: "Revival", cooldown: "One-time", level: 1 },
  { name: "Kết Nối Tâm Linh", description: "Tạo ra mối liên kết sâu sắc với fan.", effect: "+80% Fan Support", cooldown: "Passive", level: 1 },
  { name: "Hào Quang Thần Thánh", description: "Xóa bỏ mọi bình luận tiêu cực.", effect: "Purify Comments", cooldown: "300s", level: 1 },
  { name: "Thiền Định Kỹ Thuật Số", description: "Giữ bình tĩnh tuyệt đối trước mọi gạch đá.", effect: "Mental Shield", cooldown: "Passive", level: 1 },
  { name: "Cầu Nguyện Viral", description: "Tăng tỷ lệ gặp may mắn khi đăng bài.", effect: "+20% Luck", cooldown: "600s", level: 1 },
  { name: "Thần Giao Cách Cảm", description: "Hiểu ý fan mà không cần họ nói ra.", effect: "Telepathy", cooldown: "Passive", level: 1 },
  { name: "Năng Lượng Tích Cực", description: "Lan tỏa niềm vui, giảm tỷ lệ anti-fan.", effect: "-30% Toxicity", cooldown: "Passive", level: 1 },
  { name: "Lời Nguyền Scandal", description: "Khiến đối thủ gặp vận đen liên tiếp.", effect: "Bad Luck Curse", cooldown: "3600s", level: 1 },
  { name: "Khai Sáng Người Xem", description: "Nâng cao nhận thức của cộng đồng.", effect: "+40% Education", cooldown: "Passive", level: 1 },
  { name: "Vòng Tròn Bảo Vệ", description: "Tạo ra cộng đồng fan trung thành bảo vệ bạn.", effect: "Fan Shield", cooldown: "Passive", level: 1 },
  { name: "Thanh Tẩy Không Gian", description: "Loại bỏ mọi năng lượng xấu trong livestream.", effect: "Clean Energy", cooldown: "600s", level: 1 },
  { name: "Giấc Mơ Tiên Tri", description: "Thấy trước nội dung sẽ hot trong tương lai.", effect: "Future Sight", cooldown: "Passive", level: 1 },
  { name: "Hơi Thở Của Rồng", description: "Lời nói có sức mạnh lay động lòng người.", effect: "+50% Persuasion", cooldown: "300s", level: 1 },
  { name: "Ấn Ký Linh Hồn", description: "Để lại dấu ấn khó phai trong tâm trí fan.", effect: "Memorable", cooldown: "Passive", level: 1 },
  { name: "Chữa Lành Kỹ Thuật Số", description: "Giúp fan vượt qua trầm cảm qua màn hình.", effect: "Healing", cooldown: "600s", level: 1 },
  { name: "Nghi Lễ Thu Hút", description: "Thu hút hàng triệu người xem mới.", effect: "Mass Attraction", cooldown: "1200s", level: 1 },
  { name: "Lá Bài Định Mệnh", description: "Thay đổi kết quả của một sự kiện truyền thông.", effect: "Fate Change", cooldown: "One-time", level: 1 },
  { name: "Hào Quang Vô Cực", description: "Trở thành vị thần trong mắt người hâm mộ.", effect: "Deification", cooldown: "Passive", level: 1 },

  // --- CHIẾN ĐẤU & PHÒNG THỦ (COMBAT & DEFENSE) ---
  { name: "Lưỡi Kiếm Ngôn Từ", description: "Đánh bại mọi đối thủ cạnh tranh.", effect: "Competitor Silence", cooldown: "600s", level: 1 },
  { name: "Giáp Trụ Dư Luận", description: "Không bị ảnh hưởng bởi dư luận xấu.", effect: "Invulnerability", cooldown: "Passive", level: 1 },
  { name: "Phản Đòn Truyền Thông", description: "Biến scandal thành cơ hội nổi tiếng.", effect: "Counter-Attack", cooldown: "900s", level: 1 },
  { name: "Triệu Hồi Fan Cuồng", description: "Kêu gọi đội quân fan tấn công đối thủ.", effect: "Fan Raid", cooldown: "1800s", level: 1 },
  { name: "Sát Thủ Viral", description: "Tạo ra nội dung tiêu diệt mọi xu hướng khác.", effect: "Trend Killer", cooldown: "3600s", level: 1 },
  { name: "Vạn Vật Hữu Linh", description: "Thổi hồn vào sản phẩm, khiến chúng tự quảng cáo.", effect: "+70% Auto-Sales", cooldown: "Passive", level: 1 },
  { name: "Thời Không Nghịch Chuyển", description: "Quay lại thời điểm trước khi mắc lỗi truyền thông.", effect: "Undo Mistake", cooldown: "One-time", level: 1 },
  { name: "Thiên Nhãn Thông", description: "Nhìn thấu mọi thuật toán của mạng xã hội.", effect: "Algorithm Mastery", cooldown: "Passive", level: 1 },
  { name: "Phân Thân Chi Thuật", description: "Xuất hiện trên tất cả các nền tảng cùng lúc.", effect: "Omnipresence", cooldown: "1200s", level: 1 },
  { name: "Tâm Linh Tương Thông", description: "Cảm nhận được cảm xúc của fan ngay lập tức.", effect: "Empathy Link", cooldown: "Passive", level: 1 },
  { name: "Hào Quang Nhân Vật Chính", description: "Luôn là tâm điểm của mọi sự chú ý.", effect: "Protagonist Aura", cooldown: "Passive", level: 1 },
  { name: "Lời Nguyền Unfollow", description: "Khiến đối thủ bị mất lượng lớn người theo dõi.", effect: "Follower Drain", cooldown: "3600s", level: 1 },
  { name: "Phúc Lộc Thọ", description: "Tăng tuổi thọ nghề nghiệp và may mắn.", effect: "+50% Career Length", cooldown: "Passive", level: 1 },
  { name: "Càn Khôn Đại Na Di", description: "Chuyển hướng dư luận tiêu cực sang đối thủ.", effect: "Blame Shift", cooldown: "1800s", level: 1 },
  { name: "Thanh Tẩy Tâm Hồn", description: "Làm dịu đi những anti-fan hung hãn nhất.", effect: "Anti-Fan Calm", cooldown: "600s", level: 1 },
  { name: "Thiết Bị Chặn Drama", description: "Tự động xóa mọi tin đồn thất thiệt.", effect: "Drama Block", cooldown: "Passive", level: 1 },
  { name: "Pháo Đài Danh Tiếng", description: "Xây dựng hình ảnh không thể bị phá vỡ.", effect: "Unstoppable", cooldown: "Passive", level: 1 },
  { name: "Chiến Thuật Du Kích", description: "Tấn công bất ngờ vào các thị trường mới.", effect: "Surprise Entry", cooldown: "1200s", level: 1 },
  { name: "Lá Chắn Bản Quyền", description: "Ngăn chặn mọi hành vi đạo nhái nội dung.", effect: "Copyright Shield", cooldown: "Passive", level: 1 },
  { name: "Đòn Quyết Định", description: "Tạo ra một chiến dịch truyền thông hạ gục đối thủ.", effect: "Final Blow", cooldown: "One-time", level: 1 },

  // --- ĐỜI SỐNG & XU HƯỚNG (LIFESTYLE & TRENDS) ---
  { name: "Bắt Trend Thần Tốc", description: "Luôn là người đầu tiên tham gia các xu hướng mới.", effect: "First Mover", cooldown: "Passive", level: 1 },
  { name: "Phong Cách Độc Bản", description: "Tạo ra gu thời trang riêng biệt không lẫn vào đâu.", effect: "Unique Style", cooldown: "Passive", level: 1 },
  { name: "Ẩm Thực Tiên Giới", description: "Review đồ ăn khiến ai cũng phải thèm thuồng.", effect: "+40% Food Appeal", cooldown: "300s", level: 1 },
  { name: "Du Hành Không Gian", description: "Check-in tại những địa điểm không tưởng.", effect: "Travel Hype", cooldown: "1200s", level: 1 },
  { name: "Sức Khỏe Vĩnh Cửu", description: "Luôn tràn đầy năng lượng, không bao giờ mệt mỏi.", effect: "Infinite Energy", cooldown: "Passive", level: 1 },
  { name: "Trang Trí Tổ Ấm", description: "Biến nhà ở thành thiên đường sống ảo.", effect: "+30% Home Decor", cooldown: "Passive", level: 1 },
  { name: "Chăm Sóc Linh Thú", description: "Nuôi những thú cưng Cyber-Xianxia cực hiếm.", effect: "Pet Influence", cooldown: "600s", level: 1 },
  { name: "Thời Trang Tự Thân", description: "Quần áo tự thay đổi theo tâm trạng và thời tiết.", effect: "Dynamic Outfit", cooldown: "Passive", level: 1 },
  { name: "Vẻ Đẹp Không Tuổi", description: "Giữ mãi nét thanh xuân qua hàng thập kỷ.", effect: "Ageless", cooldown: "Passive", level: 1 },
  { name: "Lối Sống Tối Giản", description: "Thu hút fan bằng sự tinh tế và đơn giản.", effect: "Minimalist Charm", cooldown: "Passive", level: 1 },
  { name: "Tiệc Tùng Thần Thánh", description: "Tổ chức những buổi party hoành tráng nhất Cyber-City.", effect: "Party King/Queen", cooldown: "2400s", level: 1 },
  { name: "Kỹ Năng Sinh Tồn", description: "Sống sót và nổi tiếng trong mọi hoàn cảnh khắc nghiệt.", effect: "Survival Expert", cooldown: "Passive", level: 1 },
  { name: "Tư Duy Đột Phá", description: "Luôn có những ý tưởng điên rồ nhưng hiệu quả.", effect: "Innovation", cooldown: "Passive", level: 1 },
  { name: "Kết Nối Cộng Đồng", description: "Xây dựng bộ tộc fan lớn mạnh nhất.", effect: "Tribal Growth", cooldown: "Passive", level: 1 },
  { name: "Sức Mạnh Tri Thức", description: "Chia sẻ những kiến thức uyên bác, thu hút fan trí thức.", effect: "Intellectual Hype", cooldown: "Passive", level: 1 },
  { name: "Vận Động Viên Siêu Cấp", description: "Thực hiện những động tác thể thao phi thường.", effect: "Athletic God", cooldown: "Passive", level: 1 },
  { name: "Bậc Thầy Pha Chế", description: "Tạo ra những loại đồ uống gây nghiện.", effect: "Mixology Master", cooldown: "300s", level: 1 },
  { name: "Làm Chủ Giấc Mơ", description: "Livestream ngay trong giấc mơ của người xem.", effect: "Dream Stream", cooldown: "3600s", level: 1 },
  { name: "Hào Quang Thân Thiện", description: "Khiến ai gặp cũng thấy mến mộ ngay lập tức.", effect: "Instant Like", cooldown: "Passive", level: 1 },
  { name: "Biểu Tượng Thời Đại", description: "Ghi danh vào lịch sử của giới KOL.", effect: "Eternal Fame", cooldown: "Passive", level: 1 },

  // --- THĂNG TIẾN & TIẾN HÓA (PROGRESSION & EVOLUTION) ---
  { name: "Tu Luyện Tốc Độ", description: "Tăng 50% tốc độ thăng cấp kỹ năng.", effect: "+50% XP Gain", cooldown: "Passive", level: 1 },
  { name: "Đột Phá Thiên Cơ", description: "Tăng tỷ lệ thăng hạng vai trò thành công.", effect: "+20% Rank Up Chance", cooldown: "Passive", level: 1 },
  { name: "Tâm Pháp Thăng Hạng", description: "Giảm yêu cầu danh tiếng để lên hạng tiếp theo.", effect: "-15% Rep Req", cooldown: "Passive", level: 1 },
  { name: "Kinh Nghiệm Truyền Thừa", description: "Nhận thêm điểm tiềm năng từ thế hệ trước.", effect: "+30% Legacy Bonus", cooldown: "Passive", level: 1 },
  { name: "Linh Đan Thăng Cấp", description: "Sử dụng để tăng ngay 1 cấp cho một kỹ năng ngẫu nhiên.", effect: "Instant Level Up", cooldown: "24h", level: 1 },
  { name: "Căn Cốt Thần Thánh", description: "Mở rộng giới hạn cấp độ kỹ năng lên 150.", effect: "Level Cap +50", cooldown: "Passive", level: 1 },
  { name: "Ngộ Tính Siêu Phàm", description: "Có xác suất học được kỹ năng mới khi thăng cấp.", effect: "New Skill Chance", cooldown: "Passive", level: 1 },
  { name: "Huyết Mạch Thần Thú", description: "Tăng mạnh các chỉ số cơ bản sau mỗi lần thăng hạng.", effect: "+40% Stat Growth", cooldown: "Passive", level: 1 },
  { name: "Thiên Đạo Vận Hành", description: "Tự động thăng cấp khi đạt đủ điều kiện mà không cần đột phá.", effect: "Auto-Evolution", cooldown: "Passive", level: 1 },
  { name: "Vạn Cổ Trường Tồn", description: "Ngăn chặn việc giảm danh tiếng hoặc cấp độ do scandal.", effect: "Anti-Degradation", cooldown: "Passive", level: 1 },
  { name: "Thái Cổ Thần Lực", description: "Sức mạnh từ thời khai thiên lập địa, tăng 200% mọi chỉ số.", effect: "Celestial Power", cooldown: "Passive", level: 1 },
  { name: "Vạn Cổ Bất Diệt", description: "Khả năng duy trì danh tiếng vĩnh cửu, không bao giờ bị lãng quên.", effect: "Eternal Fame", cooldown: "Passive", level: 1 },
  { name: "Chưởng Quản Càn Khôn", description: "Thao túng xu hướng toàn cầu bằng ý nghĩ.", effect: "Universal Control", cooldown: "120s", level: 1 },
  { name: "Hư Không Chân Thân", description: "Hiện diện ở mọi nền tảng cùng lúc với sức mạnh tối đa.", effect: "Omnipresence", cooldown: "Passive", level: 1 },
  { name: "Thiên Đạo Chân Lý", description: "Lời nói trở thành chân lý, định hình lại thực tại kỹ thuật số.", effect: "Reality Warp", cooldown: "300s", level: 1 }
];

// Hàm lấy ngẫu nhiên kỹ năng từ pool
export const getRandomSkills = (count: number): KOLSkill[] => {
  const shuffled = [...SKILL_POOL].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};
